"""
A tool for generating a list of tokens for the current CPython interpreter.
"""
import datetime
import platform
import sys
import textwrap

import opcode


def main():
    now = datetime.datetime.utcnow().isoformat(sep=" ")
    content = textwrap.dedent(f"""
    # This file was generated by the Pytecode token generator.
    # This was generated for Python {platform.python_version()} on {now}. 
    _pytecode_PY_VERSION = ({sys.version_info[0]}, {sys.version_info[1]})
    """)

    for name, opcode_ in sorted(opcode.opmap.items(), key=lambda i: i[1]):
        content += f"{name.upper()} = {opcode_}\n"

    print(content)


if __name__ == "__main__":
    main()
